import pandas as pd
accessFile=pd.read_csv('newBiplabCsvFile.csv')
df=pd.DataFrame(accessFile)

# print(df.head(5))
# print(df.index)
# print(df.columns)
# print(df.isnull().sum())
# print(df['age'])
# print(df[['name','age']])
print(df.iloc[2])
print("*******************")
print(df.loc [1])
print("*********************")
print(df)
print("***********************")
print(df.iloc[0:3])
